FSM:
  Passive:
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 2]
    qs: [
      [],
      [0., 1.136, -2.297, 0., 1.136, -2.297, 0., 1.136, -2.297, 0., 1.136, -2.297],
    ]
  Velocity:
    policy_dir: ../../../logs/rsl_rl/unitree_go2_custom #../../../logs/rsl_rl/unitree_go2_velocity # ../../../logs/rsl_rl/unitree_go2_custom # ../../../logs/rsl_rl/unitree_simulation_policy_now
  SitDown:
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 2]
    qs: [
      [],
      [0.134, 1.22, -2.72, 0.134, 1.22, -2.72, 0.134, 1.3, -2.72, 0.134, 1.3, -2.72,],
    ] # [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],